"""Small interfaces for swapping providers and stores without changing the core."""

from __future__ import annotations

from typing import Any, Protocol


class VisionAdapter(Protocol):
    model_id: str

    def predict(
        self, image_bytes: bytes, context: dict[str, Any]
    ) -> tuple[list[dict[str, Any]], dict[str, Any]]: ...
    def public_config(self) -> dict[str, Any]: ...
    def seed_usage(self, rows: list[dict[str, Any]]) -> None: ...
    def estimated_cost(self) -> float: ...


class ImageStore(Protocol):
    def load(self, task: dict[str, Any]) -> bytes: ...


class PredictionStore(Protocol):
    def read(self) -> list[dict[str, Any]]: ...
    def append(self, row: dict[str, Any]) -> None: ...
    def load_manifest(self) -> dict[str, Any] | None: ...
    def save_manifest(self, manifest: dict[str, Any]) -> None: ...


class TaxonResolver(Protocol):
    def resolve_name(self, name: str) -> dict | None: ...


class ResolutionStore(Protocol):
    def get(self, task_id: str) -> dict | None: ...
    def put(self, entry: dict) -> None: ...


class AnswerExtractor(Protocol):
    identity: str
    public_config: dict[str, Any]

    def extract(self, raw_answer: str) -> dict: ...


class ExtractionStore(Protocol):
    def get(self, task_id: str) -> dict | None: ...
    def put(self, entry: dict) -> None: ...
